-- with tripdata as 
-- (
--   select *,
--     row_number() over(partition by vendorid, lpep_pickup_datetime) as rn
--   from {{ source('staging','external_green_data') }}
--   where vendorid is not null 
-- )